In [ ]:
%pip install pandas

In [2]:
# dataframe
import pandas as pd


data = {
    'name': ['Nishant','Joy','Rohan','Ajay','Heena','Payal'],
    'age':[25,26,78,45,56,23],
    'City':['mumbai','pune','jaipur','surat','bhuj','goa']
}

df = pd.DataFrame(data)
df

      name  age    City
0  Nishant   25  mumbai
1      Joy   26    pune
2    Rohan   78  jaipur
3     Ajay   45   surat
4    Heena   56    bhuj
5    Payal   23     goa

In [ ]:
# list 
data_list = [
     {'Name':'Nishant','Age':25,'Height':5.6,'City':'Mumbai'},
     {'Name':'Joy','Age':15,'Height':3.6,'City':'Pune'},
]

df1 = pd.DataFrame(data_list)
df1

In [ ]:
# arr 2d
col = ["mumbai","pune","Surat"]
df3 = pd.DataFrame([[21,22,23],[24,25,26],[27,28,29]],columns=col)
df3

In [ ]:
data = {
    'name': ['Nishant','Joy','Rohan','Ajay','Heena','Payal'],
    'age':[25,26,78,45,56,23],
    'City':['mumbai','pune','jaipur','surat','bhuj','goa']
}

df = pd.DataFrame(data)
df

In [ ]:
# head()
df.head()

In [ ]:
# top 3
df.head(3)

In [ ]:
# tail()
df.tail()

In [ ]:
df.tail(3)

In [ ]:
df.info()

In [ ]:
# summary 
df.describe()

In [22]:
print(df['name'])

0    Nishant
1        Joy
2      Rohan
3       Ajay
4      Heena
5      Payal
Name: name, dtype: object

In [25]:
df[['name','City']]

      name    City
0  Nishant  mumbai
1      Joy    pune
2    Rohan  jaipur
3     Ajay   surat
4    Heena    bhuj
5    Payal     goa

In [30]:
df.to_csv("data.csv",index=False)

In [ ]:
# data set 
# https://raw.githubusercontent.com/Pankaj-Str/Complete-Python-Mastery/refs/heads/main/53%20DataSet/online_retail_sales.csv

In [11]:
# online data raw data

data = pd.read_csv("https://raw.githubusercontent.com/Pankaj-Str/Complete-Python-Mastery/refs/heads/main/53%20DataSet/online_retail_sales.csv")

data = pd.read_csv("credit_card_transactions.csv")

data.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452,01-01-2023,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775,01-01-2023,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer
2,100002,2259,01-01-2023,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545,01-01-2023,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137,01-01-2023,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland

In [12]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      5500 non-null   int64
 1   Customer_ID         5500 non-null   int64
 2   Transaction_Date    5500 non-null   object
 3   Transaction_Type    5469 non-null   object
 4   Merchant            5476 non-null   object
 5   Category            5469 non-null   object
 6   Amount              5439 non-null   float64
 7   Payment_Mode        5485 non-null   object
 8   Transaction_Status  5424 non-null   object
 9   Location            5500 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 429.8+ KB
None

In [13]:
print(data.dtypes)

Transaction_ID          int64
Customer_ID             int64
Transaction_Date       object
Transaction_Type       object
Merchant               object
Category               object
Amount                float64
Payment_Mode           object
Transaction_Status     object
Location               object
dtype: object

In [14]:
print(data.columns.to_list())

['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Transaction_Type', 'Merchant', 'Category', 'Amount', 'Payment_Mode', 'Transaction_Status', 'Location']

In [15]:
print(data.describe())

       Transaction_ID  Customer_ID       Amount
count     5500.000000  5500.000000  5439.000000
mean    102749.500000  2989.954182  2488.180221
std       1587.857571  1153.928878  1446.216624
min     100000.000000  1000.000000     6.550000
25%     101374.750000  1988.000000  1232.595000
50%     102749.500000  3000.000000  2492.290000
75%     104124.250000  3990.000000  3766.825000
max     105499.000000  4998.000000  4997.490000

In [16]:
print(data.isnull().sum())

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Transaction_Type      31
Merchant              24
Category              31
Amount                61
Payment_Mode          15
Transaction_Status    76
Location               0
dtype: int64