In [1]:
%pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/pankajchouhan/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/pankajchouhan/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# import pandas library

import pandas as pd

In [3]:
data = {
    'Name':['Amit','Neha','Rupali','Neelam','Nishant','Kiran','Rahul','Rohan'],
    'Age':[23,34,45,56,23,10,90,34],
    'City':['Mumbai','Jaipur','Surat','Goa','Pune','Bhuj','Jodhpur','Delhi'],
    'Salary':[2000,34000,45000,78000,4500,76000,56000,45900],
    'Department':['HR','Sales','IT','Finance','HR','Sales','IT','Finance']
}

df = pd.DataFrame(data)
# print(df)
df

      Name  Age     City  Salary Department
0     Amit   23   Mumbai    2000         HR
1     Neha   34   Jaipur   34000      Sales
2   Rupali   45    Surat   45000         IT
3   Neelam   56      Goa   78000    Finance
4  Nishant   23     Pune    4500         HR
5    Kiran   10     Bhuj   76000      Sales
6    Rahul   90  Jodhpur   56000         IT
7    Rohan   34    Delhi   45900    Finance

In [4]:
# From List of Lists 

df2 = pd.DataFrame(
    data =[['Nishant',25],['Joy',30]],
    columns =['Name','Age'],
    index = ['emp1','emp2']
)

print(df2)

         Name  Age
emp1  Nishant   25
emp2      Joy   30

In [5]:
# From List of Dictionaries

records = [
    {'Name':'Joy','Age':25,'City':'Mumbai'},
    {'Name':'Nishant','Age':30,'City':'Pune'}
]

df3 = pd.DataFrame(records)
print(df3)

      Name  Age    City
0      Joy   25  Mumbai
1  Nishant   30    Pune

In [6]:
# Empty DataFrame 

df_empty = pd.DataFrame(columns=['Name','Age','Salary'])
print(df_empty)

Empty DataFrame
Columns: [Name, Age, Salary]
Index: []

In [7]:
# using numpy for create a dataframe 

# instal numpy

%pip install numpy

Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.5.3)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import numpy as np

arr = np.random.randn(5,3)
df4 = pd.DataFrame(arr,columns=['A','B','C'])
print(df4)

          A         B         C
0  0.140620 -0.230873  0.638125
1 -0.299575  0.950578 -0.891595
2 -1.730139  0.028836 -0.703313
3  0.921251 -2.463592 -1.242842
4  1.025660  0.062032 -1.440394

In [18]:
# Read CSV File 

bank_data = pd.read_csv('Data/bank.csv')

# print(bank_data) # show all data
# show only 5 rows 
# print(bank_data.head())
bank_data.head(10)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
5,35,management,single,tertiary,no,747,no,no,cellular,23,feb,141,2,176,3,failure,no
6,36,self-employed,married,tertiary,no,307,yes,no,cellular,14,may,341,1,330,2,other,no
7,39,technician,married,secondary,no,147,yes,no,cellular,6,may,151,2,-1,0,unknown,no
8,41,entrepreneur,married,tertiary,no,221,yes,no,unknown,14,may,57,2,-1,0,unknown,no
9,43,services,married,primary,no,-88,yes,yes,cellular,17,apr,313,1,147,2,failure,no

In [19]:
# Essential Inspection Methods (Always start here)

# Show First 5 rows of the DataFrame
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [21]:
# Last 3 row
df.tail(3)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [30]:
# random rows 
df.sample(2)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
4506,42,unemployed,divorced,tertiary,no,-166,no,no,cellular,29,aug,85,4,-1,0,unknown,no
2960,59,blue-collar,married,secondary,no,681,yes,no,telephone,14,apr,427,2,-1,0,unknown,no

In [32]:
# number of (row,colum)
df.shape

(4521, 17)

In [33]:
# list of columns names 
df.columns.tolist()

['age',
 'job',
 'marital',
 'education',
 'default',
 'balance',
 'housing',
 'loan',
 'contact',
 'day',
 'month',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'y']

In [34]:
# row labels 
df.index

RangeIndex(start=0, stop=4521, step=1)

In [35]:
# check datatype
df.dtypes

age          int64
job            str
marital        str
education      str
default        str
balance      int64
housing        str
loan           str
contact        str
day          int64
month          str
duration     int64
campaign     int64
pdays        int64
previous     int64
poutcome       str
y              str
dtype: object

In [36]:
# find the complete summary
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   str
 2   marital    4521 non-null   str
 3   education  4521 non-null   str
 4   default    4521 non-null   str
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   str
 7   loan       4521 non-null   str
 8   contact    4521 non-null   str
 9   day        4521 non-null   int64
 10  month      4521 non-null   str
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   str
 16  y          4521 non-null   str
dtypes: int64(7), str(10)
memory usage: 600.6 KB

In [ ]:
# Statistics (numeric)
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000
mean,41.170095,1422.657819,15.915284,263.961292,2.793630,39.766645,0.542579
std,10.576211,3009.638142,8.247667,259.856633,3.109807,100.121124,1.693562
min,19.000000,-3313.000000,1.000000,4.000000,1.000000,-1.000000,0.000000
25%,33.000000,69.000000,9.000000,104.000000,1.000000,-1.000000,0.000000
50%,39.000000,444.000000,16.000000,185.000000,2.000000,-1.000000,0.000000
75%,49.000000,1480.000000,21.000000,329.000000,3.000000,-1.000000,0.000000
max,87.000000,71188.000000,31.000000,3025.000000,50.000000,871.000000,25.000000

In [39]:
# for String / categories
df.describe(include='object')

/var/folders/72/gr4bp7zd6qggsc9h6gxnm5jw0000gn/T/ipykernel_5314/2168864718.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,job,marital,education,default,housing,loan,contact,month,poutcome,y
count,4521,4521,4521,4521,4521,4521,4521,4521,4521,4521
unique,12,3,4,2,2,2,3,12,4,2
top,management,married,secondary,no,yes,no,cellular,may,unknown,no
freq,969,2797,2306,4445,2559,3830,2896,1398,3705,4000

In [40]:
# unique count per columns 
df.nunique()

age            67
job            12
marital         3
education       4
default         2
balance      2353
housing         2
loan            2
contact         3
day            31
month          12
duration      875
campaign       32
pdays         292
previous       24
poutcome        4
y               2
dtype: int64

In [41]:
df['job'].value_counts()

job
management       969
blue-collar      946
technician       768
admin.           478
services         417
retired          230
self-employed    183
entrepreneur     168
unemployed       128
housemaid        112
student           84
unknown           38
Name: count, dtype: int64

In [42]:
# memory usage 
df.memory_usage(deep=True)

Index           132
age           36168
job          264656
marital      252508
education    259138
default      230647
balance       36168
housing      233130
loan         231262
contact      256674
day           36168
month        235092
duration      36168
campaign      36168
pdays         36168
previous      36168
poutcome     252782
y            231092
dtype: int64