- https://github.com/Pankaj-Str/Complete-Python-Mastery/issues/14

#### 1️⃣ Data Exploration and Cleaning
- Load the dataset into a Pandas DataFrame and display the first 5 rows.
- Check the shape, column names, and summary statistics of the dataset.
- Identify and handle missing values (fill or drop based on the data type).
- Convert Transaction_Date into datetime format and extract year, month, and day as new columns.
#### 2️⃣ Data Selection and Indexing
- Retrieve all transactions made in January 2024.
- Find transactions where Amount > 1000 and Transaction_Type is "Online".
- Select only Approved transactions from the dataset.

In [1]:
import pandas as pd

df = pd.read_csv("credit_card_transactions.csv")
df.head() # show only 5 row

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452.0,2023-01-01,NaN,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775.0,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,NaN
2,100002,2259.0,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545.0,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137.0,2023-01-01,ATM,NaN,Travel,2517.07,Debit Card,Approved,Matthewland

In [2]:
# find the size 
print(df.shape) # (rows,columns)

# print columns name list
print(df.columns.to_list())

# find the all into 
print(df.info())

(16500, 10)
['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Transaction_Type', 'Merchant', 'Category', 'Amount', 'Payment_Mode', 'Transaction_Status', 'Location']
<class 'pandas.DataFrame'>
RangeIndex: 16500 entries, 0 to 16499
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      16500 non-null  str
 1   Customer_ID         15167 non-null  str
 2   Transaction_Date    15131 non-null  str
 3   Transaction_Type    15132 non-null  str
 4   Merchant            15158 non-null  str
 5   Category            15144 non-null  str
 6   Amount              15100 non-null  float64
 7   Payment_Mode        15184 non-null  str
 8   Transaction_Status  15128 non-null  str
 9   Location            15175 non-null  str
dtypes: float64(1), str(9)
memory usage: 1.3 MB
None

In [3]:
# summary 
print(df.describe())

             Amount
count  15100.000000
mean   16208.393093
std    15819.878614
min        6.550000
25%     2764.082500
50%     8788.420000
75%    29613.212500
max    49998.010000

In [4]:
# find the missing values 
print(df.isnull().sum())

Transaction_ID           0
Customer_ID           1333
Transaction_Date      1369
Transaction_Type      1368
Merchant              1342
Category              1356
Amount                1400
Payment_Mode          1316
Transaction_Status    1372
Location              1325
dtype: int64

In [5]:
df['Merchant'] = df['Merchant'].fillna('Unknown')
df['Transaction_Type'] = df['Transaction_Type'].fillna('Unknown')
df['Category'] = df['Category'].fillna('Unknown')
df['Payment_Mode'] = df['Payment_Mode'].fillna('Unknown')
df['Transaction_Status'] = df['Transaction_Status'].fillna('Unknown')
df['Location'] = df['Location'].fillna('Unknown')
print(df.isnull().sum())

Transaction_ID           0
Customer_ID           1333
Transaction_Date      1369
Transaction_Type         0
Merchant                 0
Category                 0
Amount                1400
Payment_Mode             0
Transaction_Status       0
Location                 0
dtype: int64

In [6]:
df['Amount'] = df['Amount'].fillna(df['Amount'].median())
print(df.isnull().sum())

Transaction_ID           0
Customer_ID           1333
Transaction_Date      1369
Transaction_Type         0
Merchant                 0
Category                 0
Amount                   0
Payment_Mode             0
Transaction_Status       0
Location                 0
dtype: int64

In [7]:
df = df.dropna(subset='Customer_ID')
df = df.dropna(subset='Transaction_Date')
print(df.isnull().sum())

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [8]:
print(df.shape)

(13902, 10)

In [9]:
print(df.dtypes)

Transaction_ID            str
Customer_ID               str
Transaction_Date          str
Transaction_Type          str
Merchant                  str
Category                  str
Amount                float64
Payment_Mode              str
Transaction_Status        str
Location                  str
dtype: object

In [10]:
# convert Date in Datetime Datatype
df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"],errors="coerce")
print(df.dtypes)

Transaction_ID                   str
Customer_ID                      str
Transaction_Date      datetime64[us]
Transaction_Type                 str
Merchant                         str
Category                         str
Amount                       float64
Payment_Mode                     str
Transaction_Status               str
Location                         str
dtype: object

In [11]:
df["Year"] = df["Transaction_Date"].dt.year
df["Month"] = df["Transaction_Date"].dt.month
df["Day"] = df["Transaction_Date"].dt.day
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day
0,100000,4452.0,2023-01-01,Unknown,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1
1,100001,2775.0,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Unknown,2023,1,1
2,100002,2259.0,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1
3,100003,4545.0,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1
4,100004,2137.0,2023-01-01,ATM,Unknown,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1

In [12]:
# transaction in JAN
jan_2023 = df[(df["Year"] == 2023) & (df["Month"] == 1)]
jan_2023.head()

jan_2023.to_csv("jan_2023.csv")

In [15]:
# Find transactions where Amount > 5000 and Transaction_Type is "Online".
high_online_transactions = df[(df['Amount'] > 5000) & (df['Transaction_Type'] == "Online")]
print("total transactions = ",high_online_transactions.shape)
print(high_online_transactions.head())
high_online_transactions.to_csv("high_online_transactions.csv")

total transactions =  (1942, 13)
    Transaction_ID Customer_ID Transaction_Date Transaction_Type     Merchant  \
33          100033      3862.0       2023-01-02           Online         Uber
35          100035      2851.0       2023-01-02           Online  Apple Store
112         100112      4768.0       2023-01-05           Online      Walmart
170         100170      1855.0       2023-01-08           Online  Apple Store
200         100200      2340.0       2023-01-09           Online      Unknown

          Category   Amount Payment_Mode Transaction_Status  \
33     Electronics  8788.42  Credit Card           Approved
35          Travel  8788.42  Credit Card            Pending
112  Entertainment  8788.42   Debit Card           Approved
170         Dining  8788.42          UPI           Approved
200         Dining  8788.42  Credit Card            Pending

              Location  Year  Month  Day
33   East Samanthaview  2023      1    2
35      Port Katherine  2023      1    2
112      Hendersonfort  2023      1    5
170           Marytown  2023      1    8
200            Unknown  2023      1    9

In [ ]:
# Data Manipulation and Feature Engineering
# Create a new column Discounted_Amount, assuming a 5% discount on all transactions above $5000.

df['Discounted_Amount'] = df['Amount'].apply(lambda x : x * 0.95 if x > 5000 else x)
df[['Amount','Discounted_Amount']].tail() # show last 5 rows

         Amount  Discounted_Amount
16494   5460.99          5187.9405
16495  13681.52         12997.4440
16496  34951.01         33203.4595
16498  31842.40         30250.2800
16499  21091.60         20037.0200

In [18]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day,Discounted_Amount
0,100000,4452.0,2023-01-01,Unknown,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1,4520.70
1,100001,2775.0,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Unknown,2023,1,1,1437.85
2,100002,2259.0,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1,3320.52
3,100003,4545.0,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1,2659.96
4,100004,2137.0,2023-01-01,ATM,Unknown,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1,2517.07

In [20]:
# Categorize the Transaction Amount into Low, Medium, and High based on:
# Low: Below $1000
# Medium: Between $1000 - $7000
# High: Above $7000

df['Amount_Categorize'] = pd.cut(df['Amount'],
                                 bins=[-float('inf'),1000,7000,float('inf')],
                                 labels=['Low','Medium','High'])
df[['Amount','Amount_Categorize']].tail()

         Amount Amount_Categorize
16494   5460.99            Medium
16495  13681.52              High
16496  34951.01              High
16498  31842.40              High
16499  21091.60              High

In [21]:
# Find the total transaction amount per Category.
total_amount_per_category = df.groupby('Category')['Amount'].sum().reset_index()
print(total_amount_per_category)

        Category       Amount
0       Clothing  33246378.08
1         Dining  33137721.78
2    Electronics  33707596.08
3  Entertainment  33230407.34
4      Groceries  32676539.88
5         Travel  34983900.43
6        Unknown  16805759.69

In [ ]:
# Select only Approved transactions from the dataset ?

In [ ]:
# Determine the number of declined transactions per Payment_Mode ?

In [ ]:
# Identify the top 5 most frequent merchants based on transaction count. ?

In [ ]:
# Find the average transaction amount per Location ?