In [2]:
import pandas as pd
# read csv
df = pd.read_csv("sales_data.csv")
# top 5 row print 
df.head()

,order_id,date,product_name,category,sales,quantity,city
0,1,2023-12-27,Laptop,Office,252.79,6,Bangalore
1,2,2023-10-10,Monitor,Office,2113.10,9,Hyderabad
2,3,2023-10-07,Keyboard,Electronics,1033.33,9,Bangalore
3,4,2023-01-01,Headphones,Accessories,1719.16,7,Bangalore
4,5,2023-04-17,Mouse,Electronics,1422.29,1,Pune

In [3]:
# get info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      550 non-null    int64
 1   date          550 non-null    str
 2   product_name  550 non-null    str
 3   category      550 non-null    str
 4   sales         550 non-null    float64
 5   quantity      550 non-null    int64
 6   city          550 non-null    str
dtypes: float64(1), int64(2), str(4)
memory usage: 30.2 KB

In [4]:
# check datatype 
df.dtypes

order_id          int64
date                str
product_name        str
category            str
sales           float64
quantity          int64
city                str
dtype: object

In [5]:
# complete summary 
df.describe()

         order_id        sales    quantity
count  550.000000   550.000000  550.000000
mean   275.500000  2555.995036    5.643636
std    158.915596  1388.737082    2.803248
min      1.000000   105.500000    1.000000
25%    138.250000  1458.115000    3.000000
50%    275.500000  2489.125000    6.000000
75%    412.750000  3800.945000    8.000000
max    550.000000  4989.370000   10.000000

In [6]:
# check null values 
df.isnull().sum()

order_id        0
date            0
product_name    0
category        0
sales           0
quantity        0
city            0
dtype: int64