In [81]:
# %pip install pandas

In [82]:
import pandas as pd
print(pd.__version__)

2.3.1

In [83]:
# pd.Series()
data = ["java","c++","python","go","jsp","ruby","r"]

for i in range(len(data)):
    print(i,data[i])

0 java
1 c++
2 python
3 go
4 jsp
5 ruby
6 r

In [84]:
#using pandas Series()
s = pd.Series(data)
print(s)

0      java
1       c++
2    python
3        go
4       jsp
5      ruby
6         r
dtype: object

In [85]:
# using index 
indexx = [101,102,103,104,105,106,107]
s = pd.Series(data,index=indexx)
print(s)

101      java
102       c++
103    python
104        go
105       jsp
106      ruby
107         r
dtype: object

In [86]:
data = {
    'name':['Nishant','Joy','toy','roy','koy','niyo'],
    'age':[12,13,15,67,89,67],
    'city':['mumbai','pune','bhuj','surat','goa','jaipur']
}

In [87]:
indexx = [101,102,103,104,105,106]
# pd.DataFrame()
df = pd.DataFrame(data,index=indexx)
df

        name  age    city
101  Nishant   12  mumbai
102      Joy   13    pune
103      toy   15    bhuj
104      roy   67   surat
105      koy   89     goa
106     niyo   67  jaipur

In [88]:
# export file 
df.to_csv("data1.csv")

In [89]:
# export file without index
df.to_csv("data01.csv",index=False)

In [90]:
# load data from folder 
data = pd.read_csv("ecommerce_data.csv")
# load online row file
# data = pd.read_csv("https://raw.githubusercontent.com/Pankaj-Str/Complete-Python-Mastery/refs/heads/main/53%20DataSet/ecommerce_data.csv")
# print(data)

In [91]:
data.head(5) # load 5 row

,Order ID,Product,Category,Quantity Ordered,Price Each,Order Date,City,Customer ID
0,1,Laptop,Electronics,1,834.18,2024-07-28 15:26:51,Chicago,4676.0
1,2,Shoes,Apparel,4,903.27,2024-01-26 13:10:16,New York,1891.0
2,3,Laptop,Electronics,2,365.51,2024-12-02 20:36:02,Chicago,4254.0
3,4,Pillow,Home Goods,5,169.17,2024-04-27 02:18:27,Houston,2859.0
4,5,Smartphone,Electronics,5,498.51,2024-03-31 06:02:42,Phoenix,5713.0

In [92]:
# tail(5) last 5 row
data.tail(5)

,Order ID,Product,Category,Quantity Ordered,Price Each,Order Date,City,Customer ID
995,996,Pillow,Home Goods,2,752.76,2024-06-26 09:37:10,New York,3617.0
996,997,Shoes,Apparel,5,787.67,2024-07-13 13:31:12,Dallas,3102.0
997,998,Coffee Mug,Home Goods,1,718.24,2024-06-04 04:07:58,Dallas,1024.0
998,999,Blanket,Home Goods,5,650.08,2024-11-09 19:25:05,New York,9758.0
999,1000,Hat,Apparel,3,71.90,2024-04-09 23:07:43,San Diego,3170.0

In [93]:
# show info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          1000 non-null   int64
 1   Product           999 non-null    object
 2   Category          1000 non-null   object
 3   Quantity Ordered  1000 non-null   int64
 4   Price Each        996 non-null    float64
 5   Order Date        999 non-null    object
 6   City              998 non-null    object
 7   Customer ID       999 non-null    float64
dtypes: float64(2), int64(2), object(4)
memory usage: 62.6+ KB

In [94]:
data.shape # find row and column number

(1000, 8)

In [95]:
# print column name 
print(data.columns.to_list())

['Order ID', 'Product', 'Category', 'Quantity Ordered', 'Price Each', 'Order Date', 'City', 'Customer ID']

In [96]:
print(data.describe())

          Order ID  Quantity Ordered  Price Each  Customer ID
count  1000.000000       1000.000000  996.000000   999.000000
mean    500.500000          3.042000  512.690131  5354.506507
std     288.819436          1.415712  287.578143  2552.254254
min       1.000000          1.000000    5.150000  1004.000000
25%     250.750000          2.000000  265.940000  3222.000000
50%     500.500000          3.000000  514.220000  5361.000000
75%     750.250000          4.000000  770.720000  7468.000000
max    1000.000000          5.000000  999.860000  9982.000000

In [97]:
print(data.dtypes) # find the data type each column

Order ID              int64
Product              object
Category             object
Quantity Ordered      int64
Price Each          float64
Order Date           object
City                 object
Customer ID         float64
dtype: object

In [98]:
print(data.isnull().sum())

Order ID            0
Product             1
Category            0
Quantity Ordered    0
Price Each          4
Order Date          1
City                2
Customer ID         1
dtype: int64