In [ ]:
# Data Exploration and Cleaning
# Load the dataset into a Pandas DataFrame and display the first 5 rows.
# Check the shape, column names, and summary statistics of the dataset.
# Identify and handle missing values (fill or drop based on the data type).
# Convert Transaction_Date into datetime format and extract year, month, and day as new columns.

In [ ]:
# Load the dataset into a Pandas DataFrame and display the first 5 rows.
import pandas as pd

df = pd.read_csv("cc.csv")
df.head()

In [ ]:
# Check the shape, column names, and summary statistics of the dataset.
print(df.shape) #(row,col)
print(df.columns.to_list())
print('summary statistics \n ',df.describe()) # include='all'

In [ ]:
#check dtype
df.dtypes

In [ ]:
# Identify and handle missing values (fill or drop based on the data type).
print(df.isnull().sum())
# Convert Transaction_Date into datetime format and extract year, month, and day as new columns.

In [ ]:
# fill the missing value 
df['Merchant'] = df['Merchant'].fillna('Unknown')
df['Transaction_Type'] = df['Transaction_Type'].fillna('Unknown')
df['Category'] = df['Category'].fillna('Unknown')
df['Payment_Mode'] = df['Payment_Mode'].fillna('Unknown')
df['Transaction_Status'] = df['Transaction_Status'].fillna('Unknown')

# fill int values
df['Amount'] = df['Amount'].fillna(df['Amount'].median()) # mean()
print(df.isnull().sum())

In [ ]:
df.dtypes

In [ ]:
# Convert Transaction_Date into datetime format and extract year, month, and day as new columns.

df.dtypes

In [ ]:
df['Transaction_Date']  = pd.to_datetime(df['Transaction_Date'],errors='coerce')
print(df.dtypes)

In [ ]:
#  year, month, and day as new columns
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Day'] = df['Transaction_Date'].dt.day

print(df.info())

In [ ]:
df.head()
df.to_csv("clean_data.csv")

In [ ]:
# Data Selection and Indexing
# Retrieve all transactions made in January 2024.
# Find transactions where Amount > 1000 and Transaction_Type is "Online".
# Select only Approved transactions from the dataset.
df.head()

In [ ]:
# # Retrieve all transactions made in January 2023.
jan_24 = df[(df['Year'] == 2023) & ( df['Month'] == 1)] 
# print(jan_24.count())
jan_24.to_csv("jan_24.csv",index=False)

In [ ]:
# Q1 - Find transactions where Amount > 3000 and Transaction_Type is "Online".
high_transactions = df[(df['Amount'] > 3000) & (df['Transaction_Type'] == "Online")]
high_transactions.head()

In [ ]:
# Q2 - Select only Approved transactions from the dataset.
approved_transactions = df[df['Transaction_Status'] == 'Approved']
approved_transactions.head()

In [ ]:
# Data Manipulation and Feature Engineering
# Create a new column Discounted_Amount, assuming a 5% discount on all transactions above $4500.
df['Discounted_Amount'] = df['Amount'].apply(lambda x : x * 0.95 if x > 4500 else x)
df[['Amount','Discounted_Amount']].head()

In [ ]:
df.head()

In [ ]:
# Categorize the Transaction_Amount into Low, Medium, and High based on:
# Low: Below $2000
# Medium: Between $2000 - $4500
# High: Above $4500

df['Amount_Category'] = pd.cut(df['Amount'],
                               bins=[-float('inf'),2000,4500,float('inf')],
                               labels=['Low','Medium','High'])

df[['Amount','Amount_Category']].head()

# Drop the Merchant column if more than 30% of values are missing.
missing_value = df['Merchant'].isnull().mean()
print(missing_value)

if missing_value > 0.3:
    df.drop(columns=['Merchant'],inplace=True)
    print("Delete done ...")
else:
    print("no missing value found...")

In [ ]:
# Aggregation and Insights
# Find the total transaction amount per Category.
total_amount_per_category = df.groupby('Category')['Amount'].sum().reset_index()
total_amount_per_category

In [ ]:
# Determine the number of declined transactions per Payment_Mode.
decliend_transactions = df[df['Transaction_Status']=='Declined'].groupby('Payment_Mode').size().reset_index(name='declined_count')
decliend_transactions

In [ ]:
# Find the average transaction amount per Location.
avg_amount_loc = df.groupby('Location')['Amount'].mean().reset_index()
avg_amount_loc

          Location    Amount
0        Aaronfort  2429.860
1       Aaronmouth  2648.060
2        Aaronside   315.540
3       Abbottbury  1549.850
4      Abigailfort  3634.880
...            ...       ...
4658  Zacharyburgh  2430.690
4659  Zacharyhaven   830.360
4660  Zacharymouth  3508.690
4661   Zacharystad  2925.135
4662   Zavalaburgh   364.530

[4663 rows x 2 columns]

In [62]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day,Discounted_Amount,Amount_Category
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1,4294.665,High
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer,2023,1,1,1437.850,Low
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1,3320.520,Medium
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1,2659.960,Medium
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1,2517.070,Medium

In [64]:
# Identify the top 5 most frequent merchants based on transaction count (Amount).
top_merchants = df['Merchant'].value_counts().head(5).reset_index()
top_merchants

  Merchant  count
0     Uber    833
1  Walmart    818
2  BestBuy    790
3  Netflix    774
4   Amazon    769