In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime , timedelta

In [2]:
# 1 load dataset 
df = pd.read_csv("credit_card_transactions.csv")

In [3]:
# 2 check row 5 
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland

In [4]:
# number of col and row
df.shape

(5500, 10)

In [5]:
# check columns name 
df.columns.tolist()

['Transaction_ID',
 'Customer_ID',
 'Transaction_Date',
 'Transaction_Type',
 'Merchant',
 'Category',
 'Amount',
 'Payment_Mode',
 'Transaction_Status',
 'Location']

In [6]:
# summary of Statistics 
df.describe(include='all')

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
count,5500.000000,5500.000000,5500,5500,5500,5500,5500.000000,5500,5500,5500
unique,NaN,NaN,230,4,7,6,NaN,4,3,4663
top,NaN,NaN,2023-01-01,Online,Uber,Groceries,NaN,PayPal,Approved,South Christopher
freq,NaN,NaN,24,1453,833,951,NaN,1432,4698,6
mean,102749.500000,2989.954182,NaN,NaN,NaN,NaN,2492.109224,NaN,NaN,NaN
std,1587.857571,1153.928878,NaN,NaN,NaN,NaN,1444.493842,NaN,NaN,NaN
min,100000.000000,1000.000000,NaN,NaN,NaN,NaN,6.550000,NaN,NaN,NaN
25%,101374.750000,1988.000000,NaN,NaN,NaN,NaN,1236.935000,NaN,NaN,NaN
50%,102749.500000,3000.000000,NaN,NaN,NaN,NaN,2502.405000,NaN,NaN,NaN
75%,104124.250000,3990.000000,NaN,NaN,NaN,NaN,3767.957500,NaN,NaN,NaN
max,105499.000000,4998.000000,NaN,NaN,NaN,NaN,4997.490000,NaN,NaN,NaN

In [7]:
# indentify missing values 
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [8]:
# check datatype
df.dtypes

Transaction_ID          int64
Customer_ID             int64
Transaction_Date       object
Transaction_Type       object
Merchant               object
Category               object
Amount                float64
Payment_Mode           object
Transaction_Status     object
Location               object
dtype: object

In [9]:
# convert Transaction_Date to date format
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'],errors='coerce')

In [10]:
# check datatype
df.dtypes

Transaction_ID                 int64
Customer_ID                    int64
Transaction_Date      datetime64[ns]
Transaction_Type              object
Merchant                      object
Category                      object
Amount                       float64
Payment_Mode                  object
Transaction_Status            object
Location                      object
dtype: object

In [12]:
# add year , month , and day 
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Day'] = df['Transaction_Date'].dt.day

In [13]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer,2023,1,1
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1

In [14]:
# check info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      5500 non-null   int64
 1   Customer_ID         5500 non-null   int64
 2   Transaction_Date    5500 non-null   datetime64[ns]
 3   Transaction_Type    5500 non-null   object
 4   Merchant            5500 non-null   object
 5   Category            5500 non-null   object
 6   Amount              5500 non-null   float64
 7   Payment_Mode        5500 non-null   object
 8   Transaction_Status  5500 non-null   object
 9   Location            5500 non-null   object
 10  Year                5500 non-null   int32
 11  Month               5500 non-null   int32
 12  Day                 5500 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(3), int64(2), object(6)
memory usage: 494.3+ KB

In [17]:
# find the Transactions january 2023 
jan_23 = df[(df['Year'] == 2023)& (df['Month']==1)]
print(jan_23.head())

   Transaction_ID  Customer_ID Transaction_Date Transaction_Type Merchant  \
0          100000         4452       2023-01-01           Online  Walmart
1          100001         2775       2023-01-01              ATM  BestBuy
2          100002         2259       2023-01-01   Mobile Payment     Uber
3          100003         4545       2023-01-01           Online  BestBuy
4          100004         2137       2023-01-01              ATM   Amazon

   Category   Amount Payment_Mode Transaction_Status       Location  Year  \
0    Travel  4520.70   Debit Card           Approved      Jonesport  2023
1    Travel  1437.85   Debit Card           Approved  Port Jennifer  2023
2  Clothing  3320.52       PayPal           Approved     Port James  2023
3    Travel  2659.96   Debit Card           Approved     Hawkinston  2023
4    Travel  2517.07   Debit Card           Approved    Matthewland  2023

   Month  Day
0      1    1
1      1    1
2      1    1
3      1    1
4      1    1

In [19]:
# find the transactions with amount > 2500 transaction type = online 
online_1000 = df[(df['Amount'] > 2500) & (df['Transaction_Type']=='Online')]
# print(online_1000)

# create csv 
online_1000.to_csv('online2500.csv')

In [ ]:
# https://github.com/Pankaj-Str/Complete-Python-Mastery/issues/14