In [1]:
import pandas as pd

#### 1️⃣ Data Exploration and Cleaning
- Load the dataset into a Pandas DataFrame and display the first 5 rows.
- Check the shape, column names, and summary statistics of the dataset.
- Identify and handle missing values (fill or drop based on the data type).
- Convert Transaction_Date into datetime format and extract year, month, and day as new columns.

In [2]:
df = pd.read_csv('clean_cc.csv')
# print first 5 rows of the dataframe
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland

In [3]:
# Check the shape, column names, and summary statistics of the dataset.
print(df.shape)
print(df.columns)
print(df.describe())

(5500, 10)
Index(['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Transaction_Type',
       'Merchant', 'Category', 'Amount', 'Payment_Mode', 'Transaction_Status',
       'Location'],
      dtype='object')
       Transaction_ID  Customer_ID       Amount
count     5500.000000  5500.000000  5469.000000
mean    102749.500000  2989.954182  2490.842201
std       1587.857571  1153.928878  1445.469054
min     100000.000000  1000.000000     6.550000
25%     101374.750000  1988.000000  1234.880000
50%     102749.500000  3000.000000  2500.640000
75%     104124.250000  3990.000000  3767.770000
max     105499.000000  4998.000000  4997.490000

In [4]:
# Identify and handle missing values (fill or drop based on the data type).
print(df.dtypes)

Transaction_ID          int64
Customer_ID             int64
Transaction_Date       object
Transaction_Type       object
Merchant               object
Category               object
Amount                float64
Payment_Mode           object
Transaction_Status     object
Location               object
dtype: object

In [5]:
# check missing values in each column
print(df.isnull().sum())

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Transaction_Type      17
Merchant               0
Category               0
Amount                31
Payment_Mode          10
Transaction_Status     8
Location               5
dtype: int64

In [6]:
# delete location missing values rows 
df = df.dropna(subset=['Location'])
# check again missing values in each column
print(df.isnull().sum())

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Transaction_Type      16
Merchant               0
Category               0
Amount                28
Payment_Mode          10
Transaction_Status     7
Location               0
dtype: int64

In [7]:
print('check size of rows ',df.shape[0])

check size of rows  5495

In [8]:
# Handle missing
# fill mean value into Amount column
mean_amount = df['Amount'].mean()
df['Amount'] = df['Amount'].fillna(mean_amount)
# check again missing values in each column
print(df.isnull().sum())

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Transaction_Type      16
Merchant               0
Category               0
Amount                 0
Payment_Mode          10
Transaction_Status     7
Location               0
dtype: int64

In [9]:
# convert date column to datetime format
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])
# check the data types again
print(df.dtypes)

Transaction_ID                 int64
Customer_ID                    int64
Transaction_Date      datetime64[ns]
Transaction_Type              object
Merchant                      object
Category                      object
Amount                       float64
Payment_Mode                  object
Transaction_Status            object
Location                      object
dtype: object

In [10]:
# handle missing value 
df['Transaction_Type'] = df['Transaction_Type'].fillna('Unknown')
df['Payment_Mode'] = df['Payment_Mode'].fillna('Unknown')
df['Transaction_Status'] = df['Transaction_Status'].fillna('Unknown')
# check again missing values in each column
print(df.isnull().sum())

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [12]:
# Extract year, month, and day as new columns.
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Day'] = df['Transaction_Date'].dt.day

df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer,2023,1,1
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1

In [ ]:
# Retrieve all transactions made in January 2023.
jan_2023 = df[(df['Year'] == 2023) & (df['Month'] == 1)]
# print(jan_2023.head())
print("total ",jan_2023.shape[0])
jan_2023.to_csv("jan_2023.csv")

total  739

In [ ]:
# Find transactions where Amount > 4000 and Transaction_Type is "Online".
# Select only Approved transactions from the dataset.
# Select only Unknown transactions from the dataset.
# Select only ATM transactions from the dataset.