In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score , classification_report
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# load dataset
df = pd.read_csv('data.csv')

In [6]:
df.head() # show top 5 rows

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

In [7]:
# drop columns 
df = df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [8]:
df.head() #check dataset

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

In [10]:
# encode cateforical variables 
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender']) # male 1 and female 0
df = pd.get_dummies(df,columns=['Geography'],drop_first=True)

In [11]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,619,0,42.0,2,0.00,1,1.0,1.0,101348.88,1,False,False
1,608,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0,False,True
2,502,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1,False,False
3,699,0,39.0,1,0.00,2,0.0,0.0,93826.63,0,False,False
4,850,0,43.0,2,125510.82,1,NaN,1.0,79084.10,0,False,True

In [24]:
# feature and target
X = df.drop('Exited',axis=1)
y = df['Exited'] # 0 = no churn , 1 churn

In [26]:
# data split 
# traning data = 80% 
# test data = 20% = test_size = 0.2

X_train,X_test , y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
# check missing values 
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')

In [30]:
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

In [31]:
# put data into model 
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,y_train)

KNeighborsClassifier()

In [32]:
# predictions 
y_pred = model.predict(X_test)

In [33]:
# check accuracy 
print("accuracy : - ",accuracy_score(y_test,y_pred))

accuracy : -  0.7656171914042978