In [1]:
%pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/pankajchouhan/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/pankajchouhan/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

print(pd.__version__)

2.3.3

In [4]:
data = ['apple', 'banana', 'cherry','watermelon','grapes']

# series()

s = pd.Series(data)
print(s)

0         apple
1        banana
2        cherry
3    watermelon
4        grapes
dtype: object

In [5]:
# update index 
x = ['a','b','c','d','e']

s = pd.Series(data,index=x)
print(s)

a         apple
b        banana
c        cherry
d    watermelon
e        grapes
dtype: object

In [7]:
# accessing data using index
print(s[0])

print(s['a'])

apple
apple

/var/folders/f3/3kqpjfqj03s00nxsf6rppv280000gn/T/ipykernel_41406/213154325.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [11]:
# dataframe()

data = {
    'name':['joy','eha','shubham','vivek','vedant'],
    'age':[23,24,25,26,27],
    'city':['delhi','mumbai','pune','bangalore','chennai']
}

df = pd.DataFrame(data)
df

      name  age       city
0      joy   23      delhi
1      eha   24     mumbai
2  shubham   25       pune
3    vivek   26  bangalore
4   vedant   27    chennai

In [12]:
# update the index
x = ['a','b','c','d','e']
df = pd.DataFrame(data,index=x)
df

      name  age       city
a      joy   23      delhi
b      eha   24     mumbai
c  shubham   25       pune
d    vivek   26  bangalore
e   vedant   27    chennai